#!/usr/bin/env python3
"""Generate publish artifacts from skills/*/SKILL.md metadata."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
README_PATH = ROOT / "README.md"
SKILLS_README_PATH = SKILLS_DIR / "README.md"
AGENTS_PATH = ROOT / "agents" / "AGENTS.md"
ROOT_AGENTS_PATH = ROOT / "AGENTS.md"
CLAUDE_MARKETPLACE_PATH = ROOT / ".claude-plugin" / "marketplace.json"
CLAUDE_PLUGIN_PATH = ROOT / ".claude-plugin" / "plugin.json"
CURSOR_PLUGIN_PATH = ROOT / ".cursor-plugin" / "plugin.json"

README_TABLE_START = "<!-- BEGIN_SKILLS_TABLE -->"
README_TABLE_END = "<!-- END_SKILLS_TABLE -->"


@dataclass
class SkillMeta:
    name: str
    description: str
    dir_name: str
    rel_path: str


def parse_frontmatter(text: str) -> dict[str, str]:
    match = re.search(r"^---\s*\n(.*?)\n---\s*", text, re.DOTALL)
    if not match:
        return {}

    data: dict[str, str] = {}
    for line in match.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip().strip('"').strip("'")
    return data


def collect_skills() -> list[SkillMeta]:
    skills: list[SkillMeta] = []
    for child in sorted(SKILLS_DIR.iterdir()):
        if not child.is_dir():
            continue
        if child.name.startswith("."):
            continue
        skill_md = child / "SKILL.md"
        if not skill_md.exists():
            continue

        frontmatter = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        name = frontmatter.get("name", child.name)
        description = frontmatter.get("description", "").strip()
        if not description:
            description = "No description provided."
        skills.append(
            SkillMeta(
                name=name,
                description=description,
                dir_name=child.name,
                rel_path=f"skills/{child.name}",
            )
        )
    return skills


def render_skills_table(skills: list[SkillMeta]) -> str:
    lines = [
        "| Name | Description | Path |",
        "|---|---|---|",
    ]
    for skill in skills:
        lines.append(
            f"| `{skill.name}` | {skill.description} | `{skill.rel_path}/` |"
        )
    return "\n".join(lines)


def write_skills_readme(skills: list[SkillMeta]) -> None:
    table = render_skills_table(skills)
    content = (
        "# Skills Catalog\n\n"
        "<!-- Auto-generated by scripts/generate_publish_artifacts.py -->\n\n"
        "Use each skill by name (for example: `$skill-name`) or by matching the trigger description.\n\n"
        f"{table}\n"
    )
    SKILLS_README_PATH.parent.mkdir(parents=True, exist_ok=True)
    SKILLS_README_PATH.write_text(content, encoding="utf-8")


def write_agents_md(skills: list[SkillMeta]) -> None:
    lines = [
        "# AGENTS.md",
        "",
        "<!-- Auto-generated by scripts/generate_publish_artifacts.py -->",
        "",
        "This repository provides agent skills for GO/GSEA enrichment workflows.",
        "",
        "## Available Skills",
        "",
    ]
    for skill in skills:
        lines.extend(
            [
                f"- **{skill.name}**",
                f"  - Description: {skill.description}",
                f"  - Path: `{skill.rel_path}/SKILL.md`",
            ]
        )

    lines.extend(
        [
            "",
            "## Usage",
            "",
            "- Mention the skill name directly (for example: `$go-enrichment-reliability`).",
            "- Or ask for a task that matches the skill description.",
        ]
    )

    AGENTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(lines) + "\n"
    AGENTS_PATH.write_text(content, encoding="utf-8")
    ROOT_AGENTS_PATH.write_text(content, encoding="utf-8")


def update_root_readme_table(skills: list[SkillMeta]) -> None:
    if not README_PATH.exists():
        return
    content = README_PATH.read_text(encoding="utf-8")
    start_idx = content.find(README_TABLE_START)
    end_idx = content.find(README_TABLE_END)
    if start_idx == -1 or end_idx == -1 or end_idx < start_idx:
        return

    table = render_skills_table(skills)
    new_content = (
        content[: start_idx + len(README_TABLE_START)]
        + "\n"
        + table
        + "\n"
        + content[end_idx:]
    )
    README_PATH.write_text(new_content, encoding="utf-8")


def write_claude_marketplace(skills: list[SkillMeta]) -> None:
    plugins = [
        {
            "name": skill.name,
            "source": f"./{skill.rel_path}",
            "description": skill.description,
        }
        for skill in skills
    ]
    payload = {
        "$schema": "https://code.claude.com/schemas/marketplace.json",
        "name": "go-enrichment-skills",
        "owner": {"name": "Eric Mac"},
        "plugins": plugins,
    }
    CLAUDE_MARKETPLACE_PATH.parent.mkdir(parents=True, exist_ok=True)
    CLAUDE_MARKETPLACE_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def write_claude_plugin(skills: list[SkillMeta]) -> None:
    payload = {
        "name": "go-enrichment-skills",
        "version": "1.0.0",
        "description": f"GO/GSEA enrichment skills bundle ({len(skills)} skill{'s' if len(skills) != 1 else ''})",
        "author": {"name": "Eric Mac"},
    }
    CLAUDE_PLUGIN_PATH.parent.mkdir(parents=True, exist_ok=True)
    CLAUDE_PLUGIN_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def write_cursor_plugin(skills: list[SkillMeta]) -> None:
    payload = {
        "name": "go-enrichment-skills",
        "skills": "skills",
        "description": f"GO/GSEA enrichment skills bundle ({len(skills)} skill{'s' if len(skills) != 1 else ''})",
        "version": "1.0.0",
        "author": {"name": "Eric Mac"},
        "homepage": "https://github.com/ericmac/GO_enrichment_skills",
        "repository": "https://github.com/ericmac/GO_enrichment_skills",
        "license": "MIT",
        "keywords": [
            "bioinformatics",
            "gene-ontology",
            "gsea",
            "go-enrichment",
            "cell-type",
        ],
    }
    CURSOR_PLUGIN_PATH.parent.mkdir(parents=True, exist_ok=True)
    CURSOR_PLUGIN_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    skills = collect_skills()
    write_skills_readme(skills)
    write_agents_md(skills)
    update_root_readme_table(skills)
    write_claude_marketplace(skills)
    write_claude_plugin(skills)
    write_cursor_plugin(skills)
    print(f"Generated publish artifacts for {len(skills)} skill(s).")


if __name__ == "__main__":
    main()
